### ISSUE TITLE
No handlers could be found for logger "visdom"

### ISSUE THREAD

**Issue by bobpop1** [lsc19940810/SATNet#12]
No handlers could be found for logger "visdom"
Traceback (most recent call last):
  File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0dbd2b3850>: Failed to establish a new connection: [Errno 111] Connection refused',))
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/visdom/__init__.py", line 711, in _send
    data=json.dumps(msg),
  File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/visdom/__init__.py", line 677, in _handle_post
    r = self.session.post(url, data=data)
  File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0db82b86d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Exception in user code:
------------------------------------------------------------
=> no checkpoint found at ''
Traceback (most recent call last):
  File "/home/wangxuzhi/Downloads/code/SATNet-master/Semantic_Scene_Completion/SUNCG_RGBD/SATNet_Depth.py", line 405, in <module>
    main()
  File "/home/wangxuzhi/Downloads/code/SATNet-master/Semantic_Scene_Completion/SUNCG_RGBD/SATNet_Depth.py", line 397, in main
    engine.learning(model, criterion, train_dataset, val_dataset, optimizer)
  File "/home/wangxuzhi/Downloads/code/SATNet-master/Semantic_Scene_Completion/SUNCG_RGBD/engine_depth.py", line 227, in learning
    self.train(train_loader, model, criterion, optimizer, epoch)
  File "/home/wangxuzhi/Downloads/code/SATNet-master/Semantic_Scene_Completion/SUNCG_RGBD/engine_depth.py", line 299, in train
    self.on_end_epoch(True, model, criterion, data_loader, optimizer)
  File "/home/wangxuzhi/Downloads/code/SATNet-master/Semantic_Scene_Completion/SUNCG_RGBD/engine_depth.py", line 88, in on_end_epoch
    loss = self.state['meter_loss_total'] / self.state['meter_loss_num']
ZeroDivisionError: float division by zero

Process finished with exit code 1

**Comment by ShiceLiu** [comment]
> ## No handlers could be found for logger "visdom"
> Traceback (most recent call last):
> File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/visdom/**init**.py", line 711, in _send
> data=json.dumps(msg),
> File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/visdom/**init**.py", line 677, in _handle_post
> r = self.session.post(url, data=data)
> File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/sessions.py", line 578, in post
> return self.request('POST', url, data=data, json=json, **kwargs)
> File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
> resp = self.send(prep, **send_kwargs)
> File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
> r = adapter.send(request, **kwargs)
> File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
> raise ConnectionError(e, request=request)
> ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/main (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0dbd2b3850>: Failed to establish a new connection: [Errno 111] Connection refused',))
> Exception in user code:
> ## Traceback (most recent call last):
> File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/visdom/**init**.py", line 711, in _send
> data=json.dumps(msg),
> File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/visdom/**init**.py", line 677, in _handle_post
> r = self.session.post(url, data=data)
> File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/sessions.py", line 578, in post
> return self.request('POST', url, data=data, json=json, **kwargs)
> File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/sessions.py", line 530, in request
> resp = self.send(prep, **send_kwargs)
> File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/sessions.py", line 643, in send
> r = adapter.send(request, **kwargs)
> File "/home/wangxuzhi/anaconda3/envs/py27/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
> raise ConnectionError(e, request=request)
> ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0db82b86d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
> Exception in user code:
> => no checkpoint found at ''
> Traceback (most recent call last):
> File "/home/wangxuzhi/Downloads/code/SATNet-master/Semantic_Scene_Completion/SUNCG_RGBD/SATNet_Depth.py", line 405, in
> main()
> File "/home/wangxuzhi/Downloads/code/SATNet-master/Semantic_Scene_Completion/SUNCG_RGBD/SATNet_Depth.py", line 397, in main
> engine.learning(model, criterion, train_dataset, val_dataset, optimizer)
> File "/home/wangxuzhi/Downloads/code/SATNet-master/Semantic_Scene_Completion/SUNCG_RGBD/engine_depth.py", line 227, in learning
> self.train(train_loader, model, criterion, optimizer, epoch)
> File "/home/wangxuzhi/Downloads/code/SATNet-master/Semantic_Scene_Completion/SUNCG_RGBD/engine_depth.py", line 299, in train
> self.on_end_epoch(True, model, criterion, data_loader, optimizer)
> File "/home/wangxuzhi/Downloads/code/SATNet-master/Semantic_Scene_Completion/SUNCG_RGBD/engine_depth.py", line 88, in on_end_epoch
> loss = self.state['meter_loss_total'] / self.state['meter_loss_num']
> ZeroDivisionError: float division by zero
> 
> Process finished with exit code 1

Visdom is the tool which helps visualization. There are two ways to solve this problem. 
First, you can open the visdom tool even though you might not use it, which can guarantee the rightness of the program.
Second, you can comment the visdom parts in the certain files by hand, such as 'engine', 'segXX.py'.
Sorry for the unconvenient code.

Best wishes!

**Comment by bobpop1** [comment]
thank you
